Type: Socket
MonitorConfiguration: false
MonitorIntervalMilliseconds: 0



# socket specific configuration:

Id: producer
Name: Producer

SocketType: MQTT

Broker:
  HostName: "host.docker.internal"
  Port: 1883

BaseTopic: docs
PayloadType: json

DefaultPublicationOptions:
  Topic: all
  ResponseTopic: response
  QosLevel: ExactlyOnce