Startup:
  - docker
  - repository
  - languageserver
  - broker
DockerUri: npipe://./pipe/docker_engine
RepositoryUri: http://localhost:8001/
LanguageServiceUri: http://localhost:8003/
BrokerUri: 127.0.0.1:1883
BrokerWebsocketUri: 127.0.0.1:5000
RepositoryImageName: ai.hgb.runtime.repository.img
RepositoryImageTag: latest
RepositoryImageExposedPort: 7001
RepositoryContainerName: ai.hgb.runtime.repository.ctn
LanguageServiceImageName: ai.hgb.runtime.languageservice.img
LanguageServiceImageTag: latest
LanguageServiceImageExposedPort: 7003
LanguageServiceContainerName: ai.hgb.runtime.languageservice.ctn
BrokerImageName: ai.hgb.runtime.broker.img
BrokerImageTag: latest
BrokerContainerName: ai.hgb.runtime.broker.ctn
BrokerImageExposedMqttPort: 1883
BrokerImageExposedWebsocketPort: 5000
